""" Correlations that survive storing and loading values """
import unittest
from mongoengine import disconnect
from bgexplorer.models.asymmetric import (AsymmetricUncertainty,
                                          CorrelationsNotLoaded)
from bgexplorer.models.component import Component, Assembly
from bgexplorer.models.cosmogenic import (ActivatedMaterial,
                                          CosmogenicActivation,
                                          ActivationPeriod)
from bgexplorer.models.emissionspec import EmissionSpec, EmissionSource
from bgexplorer.models.hiteff import HitEfficiency
from bgexplorer.models.settings import VersionSettings
from bgexplorer.models.sourceterm import (SourceTerm, CalculatedResults,
                                          clear_results_cache)
from bgexplorer.models.common import units
from bgexplorer.models import versioncontrol as vc
from tests.dbutil import connect_test_db
from bgexplorer.models.histogram import Histogram
from tests.test_cosmogenic import copper
import numpy as np
from numpy.testing import assert_allclose


def total(quantities):
    result = None
    for q in quantities:
        result = q if result is None else result + q
    return result


class TestStoredCorrelations(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        connect_test_db()

    @classmethod
    def tearDownClass(cls):
        disconnect()

    def setUp(self):
        for cls in (VersionSettings, Component, EmissionSpec, SourceTerm,
                    CalculatedResults, HitEfficiency, ActivatedMaterial):
            cls.drop_collection()
        clear_results_cache()
        vc.create_version('main')

    def test_computed_rate(self):
        """ a rate computed from a variable is stored with it """
        x = AsymmetricUncertainty(10, 1) * units('mBq/kg')
        spec = EmissionSpec(name='e', sources=[
            EmissionSource(name='K40', rate=x * 2),
            EmissionSource(name='Co60', rate=x * 3)]).save()
        spec = EmissionSpec.objects.get(id=spec.id)
        a, b = (s.rate for s in spec.sources)
        self.assertFalse(a.m.isleaf)
        self.assertAlmostEqual((a + b).to('mBq/kg').m.s0, 5)
        self.assertAlmostEqual((a - 2 * x).to('mBq/kg').m.s0, 0)

    def test_generated_sources(self):
        """ sources generated by the settings are correlated with theirs """
        settings = VersionSettings.objects.get(version_tag='main')
        self.assertIn('Ra226', [a.newsource for a in settings.addsources])
        spec = EmissionSpec(name='e', sources=dict(
            U238='10 +- 1 mBq/kg')).save()
        spec = EmissionSpec.objects.get(id=spec.id)
        rates = {s.name: s.rate for s in spec.sources}
        # Ra226 is in equilibrium with U238, so their errors add linearly
        self.assertAlmostEqual(
            (rates['U238'] + rates['Ra226']).to('mBq/kg').m.s0, 2)
        # as does U235, from its natural abundance
        u238, u235 = (rates[n].to('mBq/kg').m for n in ('U238', 'U235'))
        self.assertAlmostEqual((u238 + u235).s0, u238.s0 + u235.s0)

    def test_activations_of_one_material(self):
        """ activations of the same material are correlated through its
        activation rates
        """
        cu = copper().save()
        specs = [CosmogenicActivation(name=f'Cu {days} d', material=cu,
                                      periods=[ActivationPeriod(
                                          duration=f'{days} day')]).save()
                 for days in (100, 200)]
        for i, spec in enumerate(specs):
            Component(name=f'c{i}', mass='1 kg', specs=[spec]).save()

        def co60():
            return [st.emissionrate for st in SourceTerm.objects(
                source__name='Co60')]
        rates = co60()
        self.assertEqual(len(rates), 2)
        expected = sum(r.to('Bq').m.s0 for r in rates)
        independent = sum(r.to('Bq').m.s0**2 for r in rates) ** 0.5
        self.assertGreater(expected, 1.2 * independent)
        self.assertAlmostEqual(total(rates).to('Bq').m.s0, expected)
        # including after loading the specs again and recalculating
        for spec in CosmogenicActivation.objects:
            spec.save()
        self.assertAlmostEqual(total(co60()).to('Bq').m.s0, expected)

    def test_stored_results(self):
        """ stored results combine as if calculated together """
        HitEfficiency(source='K40', location='loc', scalars=dict(
            v1='0.1 +- 0.01 dru/mBq'), spectra=dict(s1=Histogram(
                AsymmetricUncertainty(np.arange(5.), np.ones(5)) *
                units('dru/mBq'), np.arange(6.) * units.keV))).save()
        assay = EmissionSpec(name='assay', sources=dict(
            K40='10 +- 1 mBq/kg')).save()
        c1 = Component(name='c1', mass='1 kg', location='loc',
                       specs=[assay]).save()
        c2 = Component(name='c2', mass='3 kg', location='loc',
                       specs=[assay]).save()
        a1 = Assembly(name='a1', components=[c1, c2]).save()
        direct = CalculatedResults.for_object(a1, save=False, cache=False)

        def stored(component):
            CalculatedResults.for_object(component, cache=False)
            sts = list(SourceTerm.objects(assemblyRoot=component))
            return CalculatedResults.from_db(sts)
        parts = stored(c1) + stored(c2)
        for key in ('v1',):
            want, got = (r.scalars[key].to('dru').m for r in (direct, parts))
            self.assertAlmostEqual(got.mode, want.mode)
            self.assertAlmostEqual(got.s0, want.s0)
            self.assertAlmostEqual(got.s1, want.s1)
        want, got = (r.spectra['s1'].hist.to('dru').m
                     for r in (direct, parts))
        assert_allclose(got.mode, want.mode)
        assert_allclose(got.s0, want.s0)
        # the assay and hiteff are shared, so the errors add linearly
        each = [stored(c).scalars['v1'].to('dru').m for c in (c1, c2)]
        self.assertGreater(parts.scalars['v1'].to('dru').m.s0,
                           (each[0].s0**2 + each[1].s0**2) ** 0.5)

        # results only to show are loaded without correlations
        sts = list(SourceTerm.objects(assemblyRoot=c1))
        shown = CalculatedResults.from_db(sts, correlations=False)
        value = shown.scalars['v1']
        self.assertFalse(value.m.correlations_loaded)
        self.assertEqual(shown.scalars_expr, {})
        self.assertEqual(str(value.to('dru')), str(each[0] * units('dru')))
        with self.assertRaises(CorrelationsNotLoaded):
            shown + stored(c2)


if __name__ == '__main__':
    unittest.main()
